services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: aredl
    ports:
      - "${API_DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    networks:
      api_net:
        aliases:
          - "${DB_ALIAS:-db}"

  api:
    image: ghcr.io/all-rated-extreme-demon-list/aredl_backend_api:${COMMIT_HASH:-latest}
    ports:
      - "${API_HOST}:${API_PORT}:${API_PORT}"
    deploy:
      update_config:
            order: start-first
            failure_action: rollback
            delay: 10s
      rollback_config:
          parallelism: 1
          delay: 10s
      restart_policy:
          condition: any
          delay: 5s
    environment:
      HOST: "0.0.0.0"
      PORT: ${API_PORT}
      DOCS_API_SERVER: ${DOCS_API_SERVER}
      
      PEMONLIST_API_URL: https://pemonlist.com/api/player

      JWT_SECRET: /run/secrets/jwt_secret

      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password

      DISCORD_CLIENT_ID: /run/secrets/discord_client_id
      DISCORD_CLIENT_SECRET: /run/secrets/discord_client_secret
      DISCORD_REDIRECT_URI: /run/secrets/discord_redirect_uri
      DISCORD_BOT_TOKEN: /run/secrets/discord_bot_token

      MATVIEWS_REFRESH_SCHEDULE: /run/secrets/matviews_refresh_schedule
      LEVEL_DATA_REFRESH_SCHEDULE: /run/secrets/level_data_refresh_schedule
      DISCORD_AVATARS_REFRESH_SCHEDULE: /run/secrets/discord_avatars_refresh_schedule
      DATA_CLEANER_SCHEDULE: /run/secrets/data_cleaner_schedule
      RECURRING_SHIFTS_SCHEDULE: /run/secrets/recurring_shifts_schedule

      GOOGLE_API_KEY: /run/secrets/google_api_key
      EDEL_SHEET_ID: /run/secrets/edel_sheet_id
      NLW_SHEET_ID: /run/secrets/nlw_sheet_id

      GOOGLE_OAUTH_CLIENT: /run/secrets/google_oauth_client
      GOOGLE_OAUTH_REFRESH: /run/secrets/google_oauth_refresh
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        no-file: "true"
        loki-pipeline-stages: |
          - json:
              expressions:
                http_method: 'span."http.method"'
          - labels:
              http_method:
    depends_on:
      - db
    secrets:
      - postgres_user
      - postgres_password
      - jwt_secret
      - discord_client_id
      - discord_client_secret
      - discord_bot_token
      - source: ${DISCORD_REDIRECT_URI}
        target: discord_redirect_uri
      - matviews_refresh_schedule
      - level_data_refresh_schedule
      - recurring_shifts_schedule
      - discord_avatars_refresh_schedule
      - data_cleaner_schedule
      - google_api_key
      - edel_sheet_id
      - nlw_sheet_id
      - google_oauth_client
      - google_oauth_refresh
      
    networks:
      - api_net
         
volumes:
  db_data:
  test_db_data:

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  jwt_secret:
    external: true
  discord_client_id:
    external: true
  discord_client_secret:
    external: true
  discord_redirect_uri_prod:
    external: true
  discord_redirect_uri_dev:
    external: true
  discord_bot_token:
    external: true
  matviews_refresh_schedule:
    external: true
  level_data_refresh_schedule:
    external: true
  data_cleaner_schedule:
    external: true
  recurring_shifts_schedule:
    external: true
  discord_avatars_refresh_schedule:
    external: true
  google_api_key:
    external: true
  edel_sheet_id:
    external: true
  nlw_sheet_id:
    external: true
  google_oauth_client:
    external: true
  google_oauth_refresh:
    external: true
networks:
  api_net:
    name: ${API_NET:-api_net}
    external: true