configs:
  prometheus_yml:
    file: ./prometheus.yml.template
    
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: aredl
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    deploy:
      restart_policy:
        condition: any
        delay: 5s

  api:
    image: ghcr.io/all-rated-extreme-demon-list/aredl_backend_api:${COMMIT_HASH:-latest}
    ports:
      - "${API_HOST}:${API_PORT}:${API_PORT}"
    deploy:
      update_config:
            order: start-first
            failure_action: rollback
            delay: 10s
      rollback_config:
          parallelism: 1
          delay: 10s
      restart_policy:
          condition: any
          delay: 5s
    environment:
      HOST: "0.0.0.0"
      PORT: ${API_PORT}

      JWT_SECRET: /run/secrets/jwt_secret

      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password

      DISCORD_CLIENT_ID: /run/secrets/discord_client_id
      DISCORD_CLIENT_SECRET: /run/secrets/discord_client_secret
      DISCORD_REDIRECT_URI: /run/secrets/discord_redirect_uri

      LEADERBOARD_REFRESH_SCHEDULE: /run/secrets/leaderboard_refresh_schedule
      LEVEL_DATA_REFRESH_SCHEDULE: /run/secrets/level_data_refresh_schedule
      NOTIFICATIONS_CLEAN_SCHEDULE: /run/secrets/notifications_clean_schedule

      GOOGLE_API_KEY: /run/secrets/google_api_key
      EDEL_SHEET_ID: /run/secrets/edel_sheet_id
      NLW_SHEET_ID: /run/secrets/nlw_sheet_id
    depends_on:
      - db
    secrets:
      - postgres_user
      - postgres_password
      - jwt_secret
      - discord_client_id
      - discord_client_secret
      - discord_redirect_uri
      - leaderboard_refresh_schedule
      - level_data_refresh_schedule
      - notifications_clean_schedule
      - google_api_key
      - edel_sheet_id
      - nlw_sheet_id
  migrate:
    image: ghcr.io/all-rated-extreme-demon-list/migrate:${COMMIT_HASH:-latest}
    environment:
      AREDL_DATA_GIT: /run/secrets/aredl_data_git
      AREDL_DATA_PARENT: "/migrate_data/aredl_data"
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    volumes:
      - migrate_data:/migrate_data
    depends_on:
      - db
    secrets:
      - postgres_user
      - postgres_password
      - aredl_data_git
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
        delay: 10s
  prometheus:
    image: prom/prometheus:v2.45.0
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        sed "s|__API_PORT__|${API_PORT}|g" /etc/prometheus/prometheus.yml.template > /etc/prometheus/prometheus.yml && \
        /bin/prometheus \
          --config.file=/etc/prometheus/prometheus.yml \
          --storage.tsdb.path=/prometheus \
          --web.console.libraries=/usr/share/prometheus/console_libraries \
          --web.console.templates=/usr/share/prometheus/consoles
    configs:
      - source: prometheus_yml
        target: /etc/prometheus/prometheus.yml.template
    volumes:
      - prometheus_data:/prometheus
    ports:
      - "9080:9090"
  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--docker_only=true'
      - '--disable_metrics=disk,diskIO,network,tcp,udp,percpu,sched,process'

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_URI: db:5432/aredl?sslmode=disable
      DATA_SOURCE_USER_FILE: /run/secrets/postgres_user
      DATA_SOURCE_PASS_FILE: /run/secrets/postgres_password
    command:
      - '--web.listen-address=:9187'
    secrets:
      - postgres_user
      - postgres_password
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
         

volumes:
  db_data:
  test_db_data:
  migrate_data:
  prometheus_data:
  grafana_data:

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  jwt_secret:
    external: true
  discord_client_id:
    external: true
  discord_client_secret:
    external: true
  discord_redirect_uri:
    external: true
  leaderboard_refresh_schedule:
    external: true
  level_data_refresh_schedule:
    external: true
  notifications_clean_schedule:
    external: true
  google_api_key:
    external: true
  edel_sheet_id:
    external: true
  nlw_sheet_id:
    external: true
  aredl_data_git:
    external: true
  grafana_admin_password:
    external: true
