services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: aredl
    ports:
      - "${API_DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - api_net

  api:
    image: ghcr.io/all-rated-extreme-demon-list/aredl_backend_api:${COMMIT_HASH:-latest}
    ports:
      - "${API_HOST}:${API_PORT}:${API_PORT}"
    deploy:
      update_config:
            order: start-first
            failure_action: rollback
            delay: 10s
      rollback_config:
          parallelism: 1
          delay: 10s
      restart_policy:
          condition: any
          delay: 5s
    environment:
      HOST: "0.0.0.0"
      PORT: ${API_PORT}

      JWT_SECRET: /run/secrets/jwt_secret

      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password

      DISCORD_CLIENT_ID: /run/secrets/discord_client_id
      DISCORD_CLIENT_SECRET: /run/secrets/discord_client_secret
      DISCORD_REDIRECT_URI: /run/secrets/discord_redirect_uri

      LEADERBOARD_REFRESH_SCHEDULE: /run/secrets/leaderboard_refresh_schedule
      LEVEL_DATA_REFRESH_SCHEDULE: /run/secrets/level_data_refresh_schedule
      DATA_CLEANER_SCHEDULE: /run/secrets/data_cleaner_schedule
      RECURRING_SHIFTS_SCHEDULE: /run/secrets/recurring_shifts_schedule

      GOOGLE_API_KEY: /run/secrets/google_api_key
      EDEL_SHEET_ID: /run/secrets/edel_sheet_id
      NLW_SHEET_ID: /run/secrets/nlw_sheet_id
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                http_method: span.http.method
          - labels:
              http_method:
    depends_on:
      - db
    secrets:
      - postgres_user
      - postgres_password
      - jwt_secret
      - discord_client_id
      - discord_client_secret
      - discord_redirect_uri
      - leaderboard_refresh_schedule
      - level_data_refresh_schedule
      - recurring_shifts_schedule
      - data_cleaner_schedule
      - google_api_key
      - edel_sheet_id
      - nlw_sheet_id
    networks:
      - api_net
         
volumes:
  db_data:
  test_db_data:

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  jwt_secret:
    external: true
  discord_client_id:
    external: true
  discord_client_secret:
    external: true
  discord_redirect_uri:
    external: true
  leaderboard_refresh_schedule:
    external: true
  level_data_refresh_schedule:
    external: true
  data_cleaner_schedule:
    external: true
  recurring_shifts_schedule:
    external: true
  google_api_key:
    external: true
  edel_sheet_id:
    external: true
  nlw_sheet_id:
    external: true
networks:
  api_net:
    external: true