CREATE TABLE IF NOT EXISTS clans (
	id UUID DEFAULT uuid_generate_v4(),
	global_name VARCHAR NOT NULL,
	tag VARCHAR NOT NULL,
	description TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	UNIQUE(tag)
);

CREATE TABLE IF NOT EXISTS clan_members (
    id uuid DEFAULT uuid_generate_v4(),
	clan_id uuid NOT NULL REFERENCES clans(id) ON DELETE CASCADE ON UPDATE CASCADE,
	user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	role INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	UNIQUE(clan_id, user_id)
);