-- Your SQL goes here
ALTER TABLE aredl.records ADD COLUMN IF NOT EXISTS hide_video BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE arepl.records ADD COLUMN IF NOT EXISTS hide_video BOOLEAN NOT NULL DEFAULT FALSE;