mod addons;
mod auth_responses_addon;
mod utils;

use crate::{
    auth, clans, health, list, notifications, roles, shifts, users, utils as utils_routes,
};
use addons::{
    ExtractorResponsesAddon, OperationIdAddon, SecurityAddon, ServerAddon, StaffBadgeAddon,
};
use auth_responses_addon::AuthResponsesAddon;
use utoipa::OpenApi;

const API_DESCRIPTION: &str = "
# Welcome to the AREDL API v2 Documentation!

## Useful Links
**Base URL**: https://api.aredl.net/v2/api  
**Github Organization**: https://github.com/All-Rated-Extreme-Demon-List/  
**Public Website**: https://aredl.net  
**Discord Server**: https://discord.gg/aredl  

## Endpoints
You can find below each category of endpoints and their description:

| Category | Description |
|---|---|
| **List** | Various endpoints for fetching AREDL data automatically generated by the database |
| **List - Levels** | Endpoints for fetching and managing the list and levels data on the AREDL |
| **List - Levels (Creators)** | Endpoints for fetching and managing the creators list of a specific AREDL level |
| **List - Submissions** | Endpoints for fetching and managing AREDL submissions, both for users and staff |
| **List - Records** | Endpoints for fetching and managing AREDL records |
| **List - Packs** | Staff only endpoints used to manage AREDL packs. To fetch packs data, use Pack Tiers endpoints instead. |
| **List - Pack Tiers** | Endpoints to fetch and manage AREDL pack tiers |
| **Authentication** | Endpoints for authenticating with Discord and managing api keys |
| **Roles** | Endpoints for fetching and managing the roles and their assigned users |
| **Users** | Endpoints for fetching and managing the list of users |
| **Users - Me** | Endpoints for fetching and managing the authenticated user and other related information |
| **Users - Merges** | Endpoints for merging users and submitting/managing merge requests |
| **Clans** | Endpoints for fetching and managing clans |
| **Clans - Members** | Endpoints for fetching, inviting and managing members of a clan |
| **Shifts** | Staff endpoints to fetch and manage staff shifts for reviewing records |
| **Notifications** | Endpoints for opening a web socket to receive real time data from the API |
| **Health** | Endpoints for checking whether the API is online or not |

In addition to that, endpoints are also categorized by the type of authentication they require:

| Type | Description |
|---|---|
| **Public** | Publicly available endpoints that do not require authentication |
| **Authed User** | Endpoints that require you to be authenticated but do not require any permission |
| **Public / Authed** | Publicly available but behave differently or offer additional features if authenticated |
| **Staff Only** | Endpoints that require a specific permission |

You can find what type an endpoint is by looking at the tags at the top of its page.

## Authentication
You can authenticate using either an access token or an API key, both passed as a bearer token.

There are two types of tokens:
- **Access Token**: Used to make authenticated requests. Expires after 30 minutes.
- **Refresh Token**: Used to get a new access token. Expires after 2 weeks.

The refresh token cannot be used on classic endpoints, but is the only one that can be used on the refresh endpoint to get a new access token. If the refresh token is about to expire, it will also return a new refresh token.

API keys can be created through the AREDL website settings or the API key endpoint and have a custom lifetime. They can be used as a regular bearer token.

You can invalidate all active tokens using the Logout All endpoint.

## Response caching
API responses default to `Cache-Control: no-cache, no-store` unless an endpoint sets its own cache policy. Cacheable endpoints return one of the following policies, where `N` is the endpoint's cache lifetime in seconds:

| Cache-Control | Meaning |
|---|---|
| `public, max-age=N` | The response may be stored by shared and private caches for N seconds. |
| `private, max-age=N` | The response may be stored by private caches for N seconds, but not by shared caches. |

Endpoints with authentication-dependent caching use `public` when the request has no `Authorization` header and `private` when that header is present.

## Allowed video URL types
Some submissions endpoints accept `video_url` (completion video) and `raw_url` (raw footage):

- **Completion video (`video_url`)**: the website the video is hosted on must be one of the allowed providers below and the URL is stored in canonical form.
- **Raw footage (`raw_url`)**: accepts any valid URL. If it matches a recognized provider it is standardized, otherwise it is stored as-is.

### Completion video (`video_url`)
The following URL types are accepted (query params not listed below are ignored):

- **YouTube** (hosts: `youtube.com`, `www.youtube.com`, `m.youtube.com`, `youtu.be`)
    - `https://youtu.be/<id>`
    - `https://www.youtube.com/watch?v=<id>`
    - `https://www.youtube.com/shorts/<id>`
    - `https://www.youtube.com/live/<id>`
    - Supported query params:
        - `t` or `start`: timestamp (seconds like `90` or `1h2m3s`)
        - `list`: playlist id
    - Normalized to: `https://www.youtube.com/watch?v=<id>[&t=...][&list=...]`

- **Vimeo** (hosts: `vimeo.com`, `www.vimeo.com`, `player.vimeo.com`)
    - `https://vimeo.com/<id>`
    - `https://player.vimeo.com/video/<id>`
    - Normalized to: `https://vimeo.com/<id>`

- **Twitch** (hosts: `twitch.tv`, `www.twitch.tv`, `player.twitch.tv`)
    - `https://www.twitch.tv/videos/<id>`
    - `https://www.twitch.tv/<channel>/video/<id>`
    - `https://www.twitch.tv/<channel>/v/<id>`
    - `https://player.twitch.tv/?video=v<id>`
    - Supported query params:
        - `t` or `time`: timestamp
    - Normalized to: `https://www.twitch.tv/videos/<id>[?t=...]`

- **BiliBili** (hosts: `bilibili.com`, `www.bilibili.com`, `m.bilibili.com`)
    - `https://www.bilibili.com/video/<id>`
    - Normalized to: `https://www.bilibili.com/video/<id>`

- **Medal** (hosts: `medal.tv`, `www.medal.tv`)
    - `https://medal.tv/clips/<id>`
    - `https://medal.tv/<lang>/clips/<id>`
    - `https://medal.tv/games/<game>/clips/<id>`
    - `https://medal.tv/<lang>/games/<game>/clips/<id>`
    - Normalized to: `https://medal.tv/clips/<id>`

- **Outplayed** (hosts: `outplayed.tv`, `www.outplayed.tv`)
    - `https://outplayed.tv/<game>/<id>`
    - Normalized to: `https://outplayed.tv/media/<id>`

### Raw footage (`raw_url`)
Recognized providers include all providers listed above plus:

- **Google Drive** (host: `drive.google.com`)
    - `https://drive.google.com/file/d/<id>`
    - `https://drive.google.com/drive/folders/<id>`
    - `https://drive.google.com/open?id=<id>`
    - `https://drive.google.com/uc?id=<id>`
    - Normalized to: `https://drive.google.com/file/d/<id>` or `https://drive.google.com/drive/folders/<id>`

- **Mega** (hosts: `mega.nz`, `www.mega.nz`)
    - `https://mega.nz/file/<id>#<key>`
    - `https://mega.nz/#!<id>!<key>`
    - Normalized to: `https://mega.nz/file/<id>#<key>`

## Privilege level and Permissions
Staff endpoints require specific permissions to be accessed.

Each role has a privilege level used for role hierarchy checks, such as deciding whether a staff member can edit a role or affect another user:

| Role | Privilege Level |
|---|---|
| **AREDL+** | 5 |
| **List Helper** | 30 |
| **List Moderator** | 50 |
| **List Admin** | 90 |
| **Developer** | 100 |
| **Owner** | 110 |

Permissions are explicit grants on roles. A role can inherit grants from another role and add its own grants on top.
";

#[derive(OpenApi)]
#[openapi(
    nest(
        (path = "/{list}", api = list::ApiDoc),
        (path = "/users", api = users::ApiDoc),
        (path = "/auth", api = auth::ApiDoc),
        (path = "/roles", api = roles::ApiDoc),
        (path = "/clans", api = clans::ApiDoc),
        (path = "/notifications", api = notifications::ApiDoc),
		(path = "/health", api = health::ApiDoc),
        (path = "/shifts", api=shifts::ApiDoc),
        (path = "/utils", api=utils_routes::ApiDoc),
	)
)]
struct MainApiDoc;
#[derive(OpenApi)]
#[openapi(
    info(
        title = "AREDL API",
        version = "2.2.1",
        license(name = "MIT"),
        description = API_DESCRIPTION,
    ),
    nest(
        (path = "/api", api = MainApiDoc),
    ),
    modifiers(&SecurityAddon, &AuthResponsesAddon, &ExtractorResponsesAddon, &StaffBadgeAddon, &ServerAddon, &OperationIdAddon),
)]
pub struct ApiDoc;
